In [1]:
import xlsxwriter 
import pandas as pd

In [2]:
df = pd.read_excel('/Users/oat/Desktop/Conclude.xlsx', sheet_name= None)

In [3]:
list_set = df['Sheet1']['SET'].to_list()

In [4]:
list_mai = df['Sheet1']['mai'].to_list()

In [5]:
list_set

['2S',
 '3K-BAT',
 '7UP',
 'A',
 'AAV',
 'ABPIF',
 'ACC',
 'ACE',
 'ACG',
 'ADVANC',
 'AEONTS',
 'AFC',
 'AGE',
 'AH',
 'AHC',
 'AI',
 'AIMCG',
 'AIMIRT',
 'AIT',
 'AJ',
 'AJA',
 'AKR',
 'ALLA',
 'ALLY',
 'ALT',
 'ALUCON',
 'AMANAH',
 'AMARIN',
 'AMATA',
 'AMATAR',
 'AMATAV',
 'AMC',
 'AMR',
 'ANAN',
 'AOT',
 'AP',
 'APCO',
 'APCS',
 'APEX',
 'APURE',
 'AQ',
 'AQUA',
 'AS',
 'ASAP',
 'ASEFA',
 'ASIA',
 'ASIAN',
 'ASIMAR',
 'ASK',
 'ASP',
 'ASW',
 'AWC',
 'AYUD',
 'B',
 'B52',
 'BA',
 'BAFS',
 'BAM',
 'BANPU',
 'BAY',
 'BBL',
 'BCH',
 'BCP',
 'BCPG',
 'BCT',
 'BDMS',
 'BEAUTY',
 'BEC',
 'BEM',
 'BFIT',
 'BGC',
 'BGRIM',
 'BH',
 'BIG',
 'BJC',
 'BJCHI',
 'BKD',
 'BKI',
 'BKKCP',
 'BLA',
 'BLAND',
 'BLISS',
 'BOFFICE',
 'BPP',
 'BR',
 'BROCK',
 'BRR',
 'BRRGIF',
 'BSBM',
 'BTNC',
 'BTS',
 'BTSGIF',
 'BUI',
 'BWG',
 'B-WORK',
 'BYD',
 'CBG',
 'CCET',
 'CCP',
 'CEN',
 'CENTEL',
 'CFRESH',
 'CGD',
 'CGH',
 'CHARAN',
 'CHAYO',
 'CHG',
 'CHOTI',
 'CI',
 'CIMBT',
 'CITY',
 'CK',
 'CKP',
 'CM',
 'CMAN',
 'CMR',
 'CNT',
 'COM7',
 'COTTO',
 'CPALL',
 'CPF',
 'CPH',
 'CPI',
 'CPL',
 'CPN',
 'CPNCG',
 'CPNREIT',
 'CPT',
 'CPTGF',
 'CPW',
 'CRANE',
 'CRC',
 'CSC',
 'CSP',
 'CSR',
 'CSS',
 'CTARAF',
 'CTW',
 'CWT',
 'DCC',
 'DCON',
 'DDD',
 'DELTA',
 'DEMCO',
 'DIF',
 'DMT',
 'DOHOME',
 'DREIT',
 'DRT',
 'DTAC',
 'DTCI',
 'DUSIT',
 'EA',
 'EASON',
 'EASTW',
 'ECL',
 'EE',
 'EGATIF',
 'EGCO',
 'EKH',
 'EMC',
 'EP',
 'EPG',
 'ERW',
 'ERWPF',
 'ESSO',
 'ESTAR',
 'ETC',
 'EVER',
 'F&D',
 'FANCY',
 'FE',
 'FMT',
 'FN',
 'FNS',
 'FORTH',
 'FPT',
 'FSS',
 'FTE',
 'FTREIT',
 'FUTUREPF',
 'GAHREIT',
 'GBX',
 'GC',
 'GEL',
 'GENCO',
 'GFPT',
 'GGC',
 'GIFT',
 'GJS',
 'GL',
 'GLAND',
 'GLOBAL',
 'GLOCON',
 'GOLDPF',
 'GPI',
 'GPSC',
 'GRAMMY',
 'GRAND',
 'GREEN',
 'GROREIT',
 'GSTEEL',
 'GULF',
 'GUNKUL',
 'GVREIT',
 'GYT',
 'HANA',
 'HFT',
 'HMPRO',
 'HPF',
 'HREIT',
 'HTC',
 'HTECH',
 'HUMAN',
 'ICC',
 'ICHI',
 'IFEC',
 'IFS',
 'IHL',
 'III',
 'ILINK',
 'ILM',
 'IMPACT',
 'INET',
 'INETREIT',
 'INGRS',
 'INOX',
 'INSURE',
 'INTUCH',
 'IRC',
 'IRPC',
 'IT',
 'ITD',
 'IVL',
 'J',
 'JAS',
 'JASIF',
 'JCK',
 'JCT',
 'JKN',
 'JMART',
 'JMT',
 'JR',
 'JTS',
 'JUTHA',
 'JWD',
 'KAMART',
 'KBANK',
 'KBS',
 'KBSPIF',
 'KC',
 'KCAR',
 'KCE',
 'KDH',
 'KEX',
 'KGI',
 'KIAT',
 'KISS',
 'KKC',
 'KKP',
 'KPNPF',
 'KSL',
 'KTB',
 'KTC',
 'KTIS',
 'KWC',
 'KWG',
 'KYE',
 'L&E',
 'LALIN',
 'LANNA',
 'LEE',
 'LH',
 'LHFG',
 'LHHOTEL',
 'LHK',
 'LHPF',
 'LHSC',
 'LOXLEY',
 'LPF',
 'LPH',
 'LPN',
 'LRH',
 'LST',
 'LUXF',
 'M',
 'MACO',
 'MAJOR',
 'MAKRO',
 'MALEE',
 'MANRIN',
 'MATCH',
 'MATI',
 'MAX',
 'MBK',
 'MBKET',
 'MC',
 'M-CHAI',
 'MCOT',
 'MCS',
 'MDX',
 'MEGA',
 'MENA',
 'METCO',
 'MFC',
 'MFEC',
 'MICRO',
 'MIDA',
 'M-II',
 'MILL',
 'MINT',
 'MIPF',
 'MIT',
 'MJD',
 'MJLF',
 'MK',
 'ML',
 'MNIT',
 'MNIT2',
 'MNRF',
 'MODERN',
 'MONO',
 'M-PAT',
 'MPIC',
 'MSC',
 'M-STOR',
 'MTC',
 'MTI',
 'NC',
 'NCAP',
 'NCH',
 'NEP',
 'NER',
 'NEW',
 'NEX',
 'NFC',
 'NKI',
 'NMG',
 'NNCL',
 'NOBLE',
 'NOK',
 'NOVA',
 'NRF',
 'NSI',
 'NSL',
 'NTV',
 'NUSA',
 'NVD',
 'NWR',
 'NYT',
 'OCC',
 'OGC',
 'OHTL',
 'OISHI',
 'OR',
 'ORI',
 'OSP',
 'PACE',
 'PAE',
 'PAF',
 'PAP',
 'PATO',
 'PB',
 'PCSGH',
 'PDI',
 'PDJ',
 'PE',
 'PERM',
 'PF',
 'PG',
 'PK',
 'PL',
 'PLANB',
 'PLAT',
 'PLE',
 'PM',
 'PMTA',
 'POLAR',
 'POPF',
 'PORT',
 'POST',
 'PPF',
 'PPP',
 'PPPM',
 'PR9',
 'PRAKIT',
 'PREB',
 'PRECHA',
 'PRG',
 'PRIME',
 'PRIN',
 'PRINC',
 'PRM',
 'PRO',
 'PROSPECT',
 'PSH',
 'PSL',
 'PT',
 'PTG',
 'PTL',
 'PTT',
 'PTTEP',
 'PTTGC',
 'PYLON',
 'Q-CON',
 'QH',
 'QHHR',
 'QHOP',
 'QHPF',
 'QTC',
 'RAM',
 'RATCH',
 'RBF',
 'RCL',
 'RICHY',
 'RJH',
 'RML',
 'ROCK',
 'ROH',
 'ROJNA',
 'RPC',
 'RPH',
 'RS',
 'RSP',
 'RT',
 'S',
 'S & J',
 'S11',
 'SA',
 'SABINA',
 'SABUY',
 'SAK',
 'SAM',
 'SAMART',
 'SAMCO',
 'SAMTEL',
 'SAPPE',
 'SAT',
 'SAUCE',
 'SAWAD',
 'SAWANG',
 'SBPF',
 'SC',
 'SCB',
 'SCC',
 'SCCC',
 'SCG',
 'SCGP',
 'SCI',
 'SCM',
 'SCN',
 'SCP',
 'SDC',
 'SEAFCO',
 'SE-ED',
 'SENA',
 'SF',
 'SFLEX',
 'SFP',
 'SGP',
 'SHANG',
 'SHR',
 'SHREIT',
 'SIAM',
 'SINGER',
 'SIRI',
 'SIRIP',
 'SIS',
 'SISB',
 'SITHAI',
 'SKE',
 'SKN',
 'SKR',
 'SKY',
 'SLP',
 'SMIT',
 'SMK',
 'SMPC',
 'SMT',
 'SNC',
 'SNNP',
 'SNP',
 'SO',
 'SOLAR',
 'SORKON',
 'SPACK',
 'SPALI',
 'SPC',
 'SPCG',
 'SPG',
 'SPI',
 'SPRC',
 'SPRIME',
 'SQ',
 'SRICHA',
 'SRIPANWA',
 'SSC',
 'SSF',
 'SSP',
 'SSPF',
 'SSSC',
 'SST',
 'SSTRT',
 'STA',
 'STANLY',
 'STARK',
 'STEC',
 'STECH',
 'STGT',
 'STHAI',
 'STPI',
 'SUC',
 'SUN',
 'SUPER',
 'SUPEREIF',
 'SUSCO',
 'SUTHA',
 'SVH',
 'SVI',
 'SVOA',
 'SYMC',
 'SYNEX',
 'SYNTEC',
 'TAE',
 'TASCO',
 'TBSP',
 'TC',
 'TCAP',
 'TCC',
 'TCCC',
 'TCJ',
 'TCMC',
 'TCOAT',
 'TEAM',
 'TEAMG',
 'TFFIF',
 'TFG',
 'TFI',
 'TFMAMA',
 'TGH',
 'TGPRO',
 'TH',
 'THAI',
 'THANI',
 'THCOM',
 'THE',
 'THG',
 'THIP',
 'THL',
 'THRE',
 'THREL',
 'TIDLOR',
 'TIF1',
 'TIP',
 'TIPCO',
 'TISCO',
 'TK',
 'TKN',
 'TKS',
 'TKT',
 'TLHPF',
 'TMD',
 'TMT',
 'TNITY',
 'TNL',
 'TNPC',
 'TNPF',
 'TNR',
 'TOA',
 'TOG',
 'TOP',
 'TOPP',
 'TPA',
 'TPBI',
 'TPCS',
 'TPIPL',
 'TPIPP',
 'TPOLY',
 'TPP',
 'TPRIME',
 'TQM',
 'TR',
 'TRC',
 'TRITN',
 'TRU',
 'TRUBB',
 True,
 'TSC',
 'TSE',
 'TSI',
 'TSR',
 'TSTE',
 'TSTH',
 'TTA',
 'TTB',
 'TTCL',
 'TTI',
 'TTLPF',
 'TTT',
 'TTW',
 'TU',
 'TU-PF',
 'TVI',
 'TVO',
 'TWP',
 'TWPC',
 'TWZ',
 'TYCN',
 'U',
 'UAC',
 'UMI',
 'UNIQ',
 'UOBKH',
 'UP',
 'UPF',
 'UPOIC',
 'URBNPF',
 'UT',
 'UTP',
 'UV',
 'UVAN',
 'VARO',
 'VGI',
 'VIBHA',
 'VIH',
 'VNG',
 'VNT',
 'VPO',
 'VRANDA',
 'W',
 'WACOAL',
 'WAVE',
 'WGE',
 'WHA',
 'WHABT',
 'WHART',
 'WHAUP',
 'WICE',
 'WIIK',
 'WIN',
 'WORK',
 'WP',
 'WPH',
 'XPG',
 'ZEN']

In [6]:
df['summary 5-10']

,Time,0,1,2,3,4,5,6,7,8,...,816,817,818,819,820,821,822,823,824,825
0,2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,2021-08-27,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2841,2021-08-30,T,AJA,TOP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2842,2021-08-31,TH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2843,2021-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2844,2021-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
len(df['summary 5-10'].columns)

827

In [8]:
type(df['summary 5-10'].iloc[0,1])

float

In [9]:
#df['summary 5-10'].iloc[2841,1] = df['summary 5-10'].iloc[2841,1]+'*'

In [10]:
for i in range(len(df['summary 5-10'])):
    for t in range(1,50):
        if type(df['summary 5-10'].iloc[i,t]) == float:
            pass
        else:
            if df['summary 5-10'].iloc[i,t] in list_mai:
                df['summary 5-10'].iloc[i,t] = df['summary 5-10'].iloc[i,t] + '*'

In [11]:
df['summary 5-10']

,Time,0,1,2,3,4,5,6,7,8,...,816,817,818,819,820,821,822,823,824,825
0,2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2840,2021-08-27,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2841,2021-08-30,T*,AJA,TOP,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2842,2021-08-31,TH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2843,2021-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2844,2021-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
for i in range(len(df['summary 3-5'])):
    for t in range(1,50):
        if type(df['summary 3-5'].iloc[i,t]) == float:
            pass
        else:
            if df['summary 3-5'].iloc[i,t] in list_mai:
                df['summary 3-5'].iloc[i,t] = df['summary 3-5'].iloc[i,t] + '*'

In [13]:
df['summary 3-5'].set_index('Time ')
df['summary 5-10'].set_index('Time ')

,0,1,2,3,4,5,6,7,8,9,...,816,817,818,819,820,821,822,823,824,825
Time,,,,,,,,,,,,,,,,,,,,,
2010-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-27,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-08-30,T*,AJA,TOP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-08-31,TH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
CC = pd.ExcelWriter('/Users/oat/Desktop/Conclude_1.xlsx')
df['Sheet1'].to_excel(CC, sheet_name='name')
df['summary 5-10'].to_excel(CC, sheet_name='summary 5-10')
df['summary 3-5'].to_excel(CC, sheet_name='summary 3-5')

In [15]:
CC.close()